#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
MyConfig="\
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend web-servers
    
backend web-servers
    balance roundrobin
    server 5292-web-01 	35.172.165.52:80
    server 5292-web-02  44.200.117.48:80
"
add-apt-repository ppa:vbernat/haproxy-2.0
apt update
apt install -y haproxy
echo "$MyConfig" >> /etc/haproxy/haproxy.cfg
service haproxy start
